# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_phone', models.CharField(max_length=10)),
                ('client_email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(choices=[('wedding', 'wedding'), ('private event', 'private event'), ('company event', 'company event'), ('other', 'other')], max_length=100)),
                ('event_date', models.DateField()),
                ('start_time_known', models.BooleanField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('event_duration', models.CharField(blank=True, choices=[('less than 1 hour', 'less than 1 hour'), ('1 hour', '1 hour'), ('2 hours', '2 hours'), ('3 hours', '3 hours'), ('4 hours', '4 hours'), ('more than 4 hours', 'more than 4 hours')], max_length=100)),
                ('performers_entire_duration', models.BooleanField()),
                ('performers_duration', models.CharField(blank=True, choices=[('less than 1 hour', 'less than 1 hour'), ('1 hour', '1 hour'), ('2 hours', '2 hours'), ('3 hours', '3 hours'), ('4 hours', '4 hours'), ('more than 4 hours', 'more than 4 hours')], max_length=100)),
                ('performers_required_time', models.TimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('address_known', models.BooleanField()),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('expected_guests', models.IntegerField(blank=True, null=True)),
                ('contact_pref', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], max_length=100)),
                ('comments', models.TextField(blank=True, max_length=800)),
                ('status', models.CharField(choices=[('inquiry', 'inquiry'), ('booked', 'booked'), ('paid', 'paid')], max_length=100)),
                ('ensemble_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.Ensemble')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('instrument', models.CharField(choices=[('piano', 'piano'), ('violin', 'violin'), ('viola', 'viola'), ('cello', 'cello')], max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('audio_file', models.FileField(upload_to=b'')),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.Ensemble')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='musician_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musician_five', to='booker.Musician'),
        ),
        migrations.AddField(
            model_name='event',
            name='musician_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musician_four', to='booker.Musician'),
        ),
        migrations.AddField(
            model_name='event',
            name='musician_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musician_one', to='booker.Musician'),
        ),
        migrations.AddField(
            model_name='event',
            name='musician_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musician_three', to='booker.Musician'),
        ),
        migrations.AddField(
            model_name='event',
            name='musician_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musician_two', to='booker.Musician'),
        ),
    ]
