# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0003_auto_20170226_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time_known',
            field=models.BooleanField(default=False),
        ),
    ]
