# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0004_auto_20170226_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='performers_entire_duration',
            field=models.BooleanField(default=False),
        ),
    ]
