# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0005_auto_20170226_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address_known',
            field=models.BooleanField(default=False),
        ),
    ]
