# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0006_auto_20170226_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='photo',
            field=models.ImageField(default='ues', upload_to=b''),
            preserve_default=False,
        ),
    ]
