# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0009_auto_20170226_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.ImageField(upload_to='booker/musicians'),
        ),
    ]
