# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0011_auto_20170226_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='photo',
            field=models.ImageField(default='yes', upload_to='ensembles'),
            preserve_default=False,
        ),
    ]
