# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0012_ensemble_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='musician',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
