# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0018_auto_20170226_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensemble',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ensembles'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='musicians'),
        ),
    ]
