# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0019_auto_20170226_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deposit_duedate', models.DateField(blank=True, null=True)),
                ('balance_duedate', models.DateField(blank=True, null=True)),
                ('deposit_recieved', models.BooleanField(default=False)),
                ('balance_recieved', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.Event')),
            ],
        ),
    ]
