# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0020_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='balance_duedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deposit_duedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deposit_recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
