# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0021_auto_20170227_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='balance',
            new_name='balance_recieved',
        ),
    ]
