# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0022_auto_20170227_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quote_message',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
