# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0024_auto_20170228_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='wedding_options',
            field=models.CharField(choices=[('1', 'Ceremony Music only (including 20 minutes prelude music + 5 minutes postlude music)'), ('2', 'Ceremony Music + Cocktail Hour Music (up to 60 minutes music directly following ceremony)'), ('3', 'Full Event Music (Ceremony, Cocktail Hour, Dinner) up to 3 hours of music')], default='1', max_length=100),
        ),
    ]
