# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0025_event_wedding_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='expected_guests',
        ),
    ]
