# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0026_remove_event_expected_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_time_known',
        ),
    ]
