# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0027_remove_event_start_time_known'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact_pref',
        ),
    ]
