# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0028_remove_event_contact_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_outdoors',
            field=models.CharField(choices=[('1', 'Not Sure Yet'), ('2', 'Yes'), ('3', 'No')], default='1', max_length=20),
        ),
    ]
