# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0030_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionList',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booker.Event')),
                ('prelude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prelude', to='booker.Selection')),
            ],
        ),
    ]
