# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0031_selectionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionlist',
            name='bridal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridal', to='booker.Selection'),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='bridesmaids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='communion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communion', to='booker.Selection'),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='flowerrings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='grandmothers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='mothers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='num_bridesmaids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='num_flowers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='num_grandmothers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='num_mothers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='num_rings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other', to='booker.Selection'),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='postlude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postlude', to='booker.Selection'),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='processional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processional', to='booker.Selection'),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='recessional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recessional', to='booker.Selection'),
        ),
        migrations.AddField(
            model_name='selectionlist',
            name='unity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unity', to='booker.Selection'),
        ),
    ]
