# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0032_auto_20170301_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectionlist',
            name='bridesmaids',
        ),
        migrations.RemoveField(
            model_name='selectionlist',
            name='flowerrings',
        ),
        migrations.RemoveField(
            model_name='selectionlist',
            name='grandmothers',
        ),
        migrations.RemoveField(
            model_name='selectionlist',
            name='mothers',
        ),
        migrations.RemoveField(
            model_name='selectionlist',
            name='other',
        ),
        migrations.RemoveField(
            model_name='selectionlist',
            name='postlude',
        ),
        migrations.RemoveField(
            model_name='selectionlist',
            name='prelude',
        ),
    ]
