# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0033_auto_20170302_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address_known',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='performers_duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='performers_entire_duration',
        ),
    ]
