# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0034_auto_20170302_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs'),
        ),
    ]
