# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0035_auto_20170303_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='booker/songs'),
        ),
    ]
