# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0036_auto_20170303_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensemble',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='booker/ensembles'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='booker/musicians'),
        ),
    ]
