# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:24
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0038_auto_20170303_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionlist',
            name='event',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booker.Event'),
        ),
    ]
