# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0041_auto_20170303_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='arrangement',
            field=models.ManyToManyField(blank=True, related_name='arrangement', to='booker.Ensemble'),
        ),
    ]
