# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:05
from __future__ import unicode_literals

import booker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0052_auto_20170306_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensemble',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=booker.models.upload_media_to),
        ),
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=booker.models.upload_media_to),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=booker.models.upload_media_to),
        ),
    ]
