# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:20
from __future__ import unicode_literals

import booker.models
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0053_auto_20170310_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=booker.models.upload_media_to),
        ),
    ]
