# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:00
from __future__ import unicode_literals

import booker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0056_auto_20170314_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=booker.models.upload_media_to),
        ),
    ]
