# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0058_auto_20170314_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='musician',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='images/', width_field='width'),
        ),
    ]
