# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:31
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0060_musician_ppoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='image PPOI'),
        ),
    ]
