# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0061_auto_20170314_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='image Height'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='image Width'),
        ),
    ]
