# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0063_auto_20170314_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image height'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='images/', verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image width'),
        ),
    ]
