# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:43
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0065_auto_20170314_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=django.utils.timezone.now, height_field='height', upload_to='images/', verbose_name='Image', width_field='width'),
            preserve_default=False,
        ),
    ]
