# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0066_auto_20170314_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
        migrations.AlterField(
            model_name='ensemble',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(default=django.utils.timezone.now, height_field='height', upload_to='images/ensembles/', verbose_name='Image', width_field='width'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='images/musicians/', verbose_name='Image', width_field='width'),
        ),
    ]
